### ISSUE TITLE
What change you make?

### ISSUE THREAD

**Issue by gnsci** [aybora/CVPR2020-Anti-UAV-Label-Correction-by-OGAM#1]
Excuse me, I just want to know what change you make for this datasets?

**Comment by aybora** [comment]
Hello there,

Some erroneous annotations were existed in original dataset labeling, mostly box shifts. We have corrected some of them with a semi automated method, if applicable.

You can check our paper which includes the method if you are interested: https://arxiv.org/abs/2004.01059

**Comment by gnsci** [comment]
To be honest, I really want to know,  in this competition , I see the max submissions total is 5. Why we can see 9, 7, 6 entries in the table?







在 2020-04-12 22:11:16，"aybora" <notifications@github.com> 写道：

Closed #1.

**Comment by aybora** [comment]
Hello again,

We are not organizing the competition. In fact, we are one of the competitors. To contact with the organizers, you can follow the official website: https://anti-uav.github.io

**Comment by gnsci** [comment]
Sorry to bother you


| |
聂世超
|
|
邮箱：18292804656@163.com
|

签名由 网易邮箱大师 定制

On 04/14/2020 19:47, aybora wrote:

Hello again,

We are not organizing the competition. In fact, we are one of the competitors. To contact with the organizers, you can follow the official website: https://anti-uav.github.io
